openapi: 3.0.0
info:
  title: Faculty API
  version: 1.0.0
paths:
  /lecturers:
    get:
      summary: Retrieve a list of all lecturers
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    staffNumber:
                      type: string
                    officeNumber:
                      type: string
                    staffName:
                      type: string
                    title:
                      type: string
                    courses:
                      type: array
                      items:
                        type: object
                        properties:
                          courseName:
                            type: string
                          courseCode:
                            type: string
                          nqfLevel:
                            type: integer
    post:
      summary: Add a new lecturer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                staffNumber:
                  type: string
                officeNumber:
                  type: string
                staffName:
                  type: string
                title:
                  type: string
                courses:
                  type: array
                  items:
                    type: object
                    properties:
                      courseName:
                        type: string
                      courseCode:
                        type: string
                      nqfLevel:
                        type: integer
      responses:
        '201':
          description: Lecturer added successfully
        '400':
          description: Bad Request

  /lecturers/{staffNumber}:
    get:
      summary: Retrieve details of a specific lecturer by staff number
      parameters:
        - in: path
          name: staffNumber
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  staffNumber:
                    type: string
                  officeNumber:
                    type: string
                  staffName:
                    type: string
                  title:
                    type: string
                  courses:
                    type: array
                    items:
                      type: object
                      properties:
                        courseName:
                          type: string
                        courseCode:
                          type: string
                        nqfLevel:
                          type: integer
        '404':
          description: Lecturer not found

    put:
      summary: Update an existing lecturer's information
      parameters:
        - in: path
          name: staffNumber
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                officeNumber:
                  type: string
                staffName:
                  type: string
                title:
                  type: string
                courses:
                  type: array
                  items:
                    type: object
                    properties:
                      courseName:
                        type: string
                      courseCode:
                        type: string
                      nqfLevel:
                        type: integer
      responses:
        '200':
          description: Lecturer updated successfully
        '400':
          description: Bad Request
        '404':
          description: Lecturer not found

    delete:
      summary: Delete a lecturer's record by staff number
      parameters:
        - in: path
          name: staffNumber
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Lecturer deleted successfully
        '404':
          description: Lecturer not found

  /courses/{courseCode}/lecturers:
    get:
      summary: Retrieve all lecturers that teach a certain course
      parameters:
        - in: path
          name: courseCode
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    staffNumber:
                      type: string
                    officeNumber:
                      type: string
                    staffName:
                      type: string
                    title:
                      type: string
                    courses:
                      type: array
                      items:
                        type: object
                        properties:
                          courseName:
                            type: string
                          courseCode:
                            type: string
                          nqfLevel:
                            type: integer
        '404':
          description: Course not found

  /offices/{officeNumber}/lecturers:
    get:
      summary: Retrieve all lecturers that sit in the same office
      parameters:
        - in: path
          name: officeNumber
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    staffNumber:
                      type: string
                    officeNumber:
                      type: string
                    staffName:
                      type: string
                    title:
                      type: string
                    courses:
                      type: array
                      items:
                        type: object
                        properties:
                          courseName:
                            type: string
                          courseCode:
                            type: string
                          nqfLevel:
                            type: integer
        '404':
          description: Office not found
